[env:wt32-eth01]
platform = espressif32
board = wt32-eth01
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.12
    mathieucarbou/AsyncTCP @ ^3.3.1
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.3.0
